FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY data ./data

ENV PYTHONUNBUFFERED=1

EXPOSE 8000
EXPOSE 8001
